image: node:latest

stages:
  - build
  - test
  - deploy

#cache:
#  paths:
#    - node_modules/

#install_dependencies:
#  stage: build
#  script:
#    - npm install
#  artifacts:
#    paths:
#      - node_modules/

#testing:
#  stage: test
#  script:
#    - npm test

build_android_files:
  image: beevelop/cordova:latest
  only:
    - master
  stage: build
  artifacts:
    paths:
    - /AndroidAPK/platforms/android/app/build/outputs/apk/release/
    
  script:
    - cordova create AndroidAPK
    - cd AndroidAPK
    - cordova platform add android
    - rm -rf www/
    - cd ..
    - ls
#    - cp -r www/ /AndroidAPK/www/
    - cd AndroidAPK
    - ls
#    - cordova build android --release

#deploy_to_website:
#  only:
#    - master
#  stage: deploy
#  script:
#  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
#  - eval $(ssh-agent -s)
#  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
#  - mkdir -p ~/.ssh
#  - chmod 700 ~/.ssh
#  - ssh-keyscan 138.68.70.61 >> ~/.ssh/known_hosts
#  - chmod 644 ~/.ssh/known_hosts
#  - rm -rf node_modules/
#  - cd ..
#  - scp -rp Alekulator/ root@138.68.70.61:/root/
#  - ssh 138.68.70.61 -p 22 -l root -t "cd Alekulator && npm install"