before_script:

  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  - eval $(ssh-agent -s)

  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

test:
  script:
 #  - ssh -T root@138.68.70.61
  - scp -P 22 -r www/ root@138.68.70.61/HybridApp/App/