image: node:latest

stages:
  - build
  - test
  - deploy
  
cache:
  paths:
    - node_modules/

before_script:
  #SSH stuff
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan 138.68.70.61 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test_program:
  stage: test
  script:
    - npm test
  
build_android_files:
  stage: build
  script:
    - ls
    
deploy_to_website:
  stage: deploy
  script:
  - rmdir node_modules/
  - cd ..
  - scp -rp Alekulator/ root@138.68.70.61:/root/
