image: node:latest

cache:
  paths:
    - node_modules/

before_script:
 - apt-get update -qq && apt-get install -y -qq sshpass

deploy_stage:
  stage: deploy
  environment: Staging
  only:
    - master
  script:
    - rm ./package-lock.json
    - npm install
    - ls
    - sshpass -V
    - ssh -o StrictHostKeyChecking=no root@138.68.70.61
    - export SSHPASS=$USER_PASS 
    - sshpass -e scp -o stricthostkeychecking=yes -r ./ root@138.68.70.61:/App

deploy_production:
  stage: deploy
  environment: Production
  only:
    - tags
  script:
    - rm ./package-lock.json
    - npm install
    - ls
    - sshpass -V
    - ssh -o StrictHostKeyChecking=no root@138.68.70.61
    - export SSHPASS=$USER_PASS 
    - sshpass -e scp -o stricthostkeychecking=yes -r ./ root@138.68.70.61:/App