before_script:

  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan 138.68.70.61 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts


test:
  script:
#   - ssh -T root@138.68.70.61
  - pwd
  #- scp ./ root@138.68.70.61 -r -P 22
  - cd ..
  - ls
  - scp -rp test_1/ root@138.68.70.61:/root/
